version: '3.9'

services:
  api-gateway:
    image: nginx:alpine
    container_name: "${PROJECT_NAME}-api-gateway"
    ports:
      - "${API_GATEWAY_PORT}:80"
    volumes:
      - ./.docker/gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.docker/gateway/cors.conf:/etc/nginx/cors.conf:ro
      # - ./nginx/logs:/var/log/nginx
    depends_on:
      - products-service
      - orders-service
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O- http://localhost/health >/dev/null 2>&1 || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "${PROJECT_NAME}-rabbitmq"
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-orders-service"
    depends_on:
      - orders-db
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./orders-service:/var/www/html
      - ./shared-bundle:/var/www/html/shared-bundle
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public", "public/index.php"]
    networks:
      - orders-network
      - default

  orders-db:
    image: postgres:16
    container_name: "${PROJECT_NAME}-orders-db"
    environment:
      POSTGRES_DB: ${ORDERS_DB_NAME}
      POSTGRES_USER: ${ORDERS_DB_USER}
      POSTGRES_PASSWORD: ${ORDERS_DB_PASS}
    restart: unless-stopped
    volumes:
      - order_data:/var/lib/postgresql/data
    ports:
      - "${ORDERS_DB_PORT}:5432"
    networks:
      - orders-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${ORDERS_DB_USER} -d ${ORDERS_DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  products-service:
    build:
      context: ./products-service
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-products-service"
    depends_on:
      - products-db
      - rabbitmq
    restart: unless-stopped
    volumes:
      - ./products-service:/var/www/html
      - ./shared-bundle:/var/www/html/shared-bundle
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public", "public/index.php"]
    networks:
      - products-network
      - default

  products-db:
    image: postgres:16
    container_name: "${PROJECT_NAME}-products-db"
    environment:
      POSTGRES_DB: ${PRODUCTS_DB_NAME}
      POSTGRES_USER: ${PRODUCTS_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCTS_DB_PASS}
    restart: unless-stopped
    volumes:
      - product_data:/var/lib/postgresql/data
    ports:
      - "${PRODUCTS_DB_PORT}:5432"
    networks:
      - products-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${PRODUCTS_DB_USER} -d ${PRODUCTS_DB_NAME}'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
  orders-network:
  products-network:

volumes:
  product_data:
  order_data:
